version: '3'
services:
  postgres:
    image: "postgres"
    container_name: postgres
    restart: always
    environment :
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : password
      POSTGRES_DB : 'grafana'
    volumes:
    - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  grafana: 
    container_name: grafana
    image: "grafana/grafana"
    restart: unless-stopped
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    env_file:
      - graf.env

  nifi:
    container_name: nifi
    image: apache/nifi:latest
    restart: unless-stopped
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME : admin
      SINGLE_USER_CREDENTIALS_PASSWORD : adminadmin123
      # NIFI_HOME : /opt/nifi/nifi-current
      # NIFI_LOG_DIR : /opt/nifi/nifi-current/logs
      # NIFI_PID_DIR : /opt/nifi/nifi-current/run
      # NIFI_BASE_DIR  : /opt/nifi
      NIFI_WEB_HTTP_PORT : '8443'
    ports:
      - 8443:8443
    # volumes:
    #   - ./postgresql-42.5.0.jar :./opt/nifi/nifi-current
